GET http://localhost:3000

###
GET http://localhost:3000/routes

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "testRoute",
    "source_id": "1",
    "destination_id": "2"
}

### Get Place Id Maps
GET http://localhost:3000/places?text=av felipe schmidt, braço do norte, 100

### Get directions from two places
GET http://localhost:3000/directions?originId=EkhBdi4gRmVsaXBlIFNjaG1pZHQsIDEwMDAgLSBJbnNzLCBCcmHDp28gZG8gTm9ydGUgLSBTQywgODg3NTAtMDAwLCBCcmFzaWwiMRIvChQKEgmz5cgUcBAhlRGSN14rsM60oxDoByoUChIJybQuy2YQIZURiWBfknZG4y8&destinationId=EkxBdi4gRmVsaXBlIFNjaG1pZHQsIDEwMCAtIFZpbGEgTm92YSwgQnJhw6dvIGRvIE5vcnRlIC0gU0MsIDg4NzUwLTAwMCwgQnJhc2lsIjASLgoUChIJ055DpHYQIZUR7LLGpFNvXsoQZCoUChIJybQuy2YQIZURiWBfknZG4y8 
