GET http://localhost:3000

###
GET http://localhost:3000/routes

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "testRoute",
    "source_id": "1",
    "destination_id": "2"
}

### Get Place Id Maps
GET http://localhost:3000/places?text=av felipe schmidt, braço do norte, 1000
