GET http://localhost:3000

###
GET http://localhost:3000/routes

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "testRoute",
    "source_id": "1",
    "destination_id": "2"
}