version: '3'

services:
  app:
    container_name: app_nest
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - .:/home/node/app
  
  db:
    build: ./db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: db
    volumes:
       - mongodb_data:/data/db

  redis:
    image: redis:7.0.8-alpine

volumes:
  mongodb_data:
    driver: local