version: '3'

services:
  mysql: 
    image: mysql:8
    container_name: go_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=routes
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql