version: '3'

services:
  mysql: 
    image: mysql:8
    container_name: go_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=routes
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    container_name: go_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./.docker/prometheus:/etc/prometheus
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: go_grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./.docker/grafana_data:/var/lib/grafana