version: '3'

services:
  app:
    container_name: app_next
    build: .
    ports: 
      - "3001:3000"
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"